### ISSUE TITLE
Can the VM0 boot up with GUI so far?

### ISSUE THREAD

**Issue by Rasterer** [minosproject/linux-raspberry#1]
Hi, Min
I am very interested in this project. Would you please kindly provide some status regarding display function? Does this support virtio-gpu now? Can the VM0 boot up with GUI(either with virtio-gpu or with pass-through HW access)?

**Comment by lemin9538** [comment]
Hi Rasterer
1 - the VM0 can boot with GUI with pass-though HW access. you can connect a HDMI screen to the board

2 - currently do not support virtio-gpu

**Comment by Rasterer** [comment]
Thanks very much for quick reply. This is a great project for someone want to try ARM virtualization. And also looking forward to the virtio-gpu support.
